from .NgAutomatePermission import (
    NGAUTOMATE_ACCESS_ALL_ORGS,
    NGAUTOMATE_ACCESS_OWN_ORG,
    NGAUTOMATE_ACCESS_PERM,
)

__all__ = ["NGAUTOMATE_ACCESS_ALL_ORGS", "NGAUTOMATE_ACCESS_OWN_ORG", "NGAUTOMATE_ACCESS_PERM"]
