# Same codes QXcel puts in its tokens ("MODULE:ACTION:SCOPE").
NGAUTOMATE_ACCESS_ALL_ORGS = "NGAUTOMATE:ACCESS:ALL_ORGS"
NGAUTOMATE_ACCESS_OWN_ORG = "NGAUTOMATE:ACCESS:OWN_ORG"

NGAUTOMATE_ACCESS_PERM = [NGAUTOMATE_ACCESS_ALL_ORGS, NGAUTOMATE_ACCESS_OWN_ORG]
