from enum import Enum


class ErrorCode(str, Enum):
    """Same codes as QXcel where they overlap, so the QXcel UI handles them the same way."""

    INVALID_INPUT = "INVALID_INPUT"
    INVALID_ARCHIVE = "INVALID_ARCHIVE"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    CONNECTION_NOT_FOUND = "CONNECTION_NOT_FOUND"

    GIT_FETCH_FAILED = "GIT_FETCH_FAILED"
    SANDBOX_FAILED = "SANDBOX_FAILED"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
